iaas_settings:
  compilation_cloud_properties:
    availability_zone: REPLACE_WITH_DIEGO_WINDOWS_SUBNET_AZ
    instance_type: c3.large
  resource_pool_cloud_properties:
  - name: cell_windows_z1
    cloud_properties:
      availability_zone: REPLACE_WITH_DIEGO_WINDOWS_SUBNET_AZ
      instance_type: m3.medium
      ephemeral_disk:
        size: 20480
  - name: cell_windows_z2
    cloud_properties: {} # UNUSED
  - name: cell_windows_z3
    cloud_properties: {} # UNUSED
  stemcell:
    name: bosh-aws-xen-hvm-windows-stemcell-go_agent
    version: REPLACE_WITH_BOSH_WINDOWS_STEMCELL_VERSION
  subnet_configs:
  - name: diego1_windows
    subnets:
    - cloud_properties:
        subnet: REPLACE_WITH_DIEGO_WINDOWS_SUBNET_ID
      dns: [10.0.0.2]
      gateway: 10.0.20.1
      range: 10.0.20.0/24
      reserved: ["10.0.20.2 - 10.0.20.3"]
  - name: diego2_windows
    subnets: [] #THIS IS AN UNUSED SUBNET
  - name: diego3_windows
    subnets: [] #THIS IS AN UNUSED SUBNET
